{
 "title": "QR",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "uid" },
   { "name": "name" }
  ]
 },
 "panels": [
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PM25 ug/m3",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PM25{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Temperatura ºC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Temperature{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Humedad %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Humidity{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}